### ISSUE TITLE
Can we access the wallpapers ?

### ISSUE THREAD

**Issue by alizeegagnon** [deviantfero/wpgtk-colorschemes#2]
Hi, I use wpgtk as a wallpaper manager as well as a colorscheme manager. As such I would like to be able to download the wallpapers that inspired your schemes. 

For example, in the bikes.json file, theres a reference to the image bikejpn.jpg:
`"wallpaper": "/home/fernando/.config/wpg/wallpapers/bikejpn.jpg"`

I would also enjoy having access to the wallpapers displayed in the demo on the wpgtk project (those that can be seen in the user gallery and personal gallery).

I'm aware this may not be a real issue, but I don't know where else to ask about this ! Thanks for the work you put into this.

**Comment by deviantfero** [comment]
your best bet are my reddit posts in /r/unixporn each has a recopilation of a few of them, I'll share some albums here:

https://imgur.com/a/uQeyhsJ
https://imgur.com/a/2W1mQjN

found the issue, thanks, I want to keep this repository as light as possible, but I might add them in the future as a URL in the `readme.md`, you could help me out with that if you'd like.

I'll close this issue, also I'm always open to direct emails for things like this, my email is on my profile, so that's a way you can reach out too.
